
package lk.dialog.cg.service;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CGWebService", targetNamespace = "urn:lk.dialog.cg.ws", wsdlLocation = "http://172.26.1.40:8080/CGWebService?wsdl")
public class CGWebService
        extends Service {

    private final static URL CGWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CGWEBSERVICE_EXCEPTION;
    private final static QName CGWEBSERVICE_QNAME = new QName("urn:lk.dialog.cg.ws", "CGWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.26.29.202:8989/CGWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CGWEBSERVICE_WSDL_LOCATION = url;
        CGWEBSERVICE_EXCEPTION = e;
    }

    public CGWebService() {
        super(__getWsdlLocation(), CGWEBSERVICE_QNAME);
    }

    // public CGWebService(WebServiceFeature... features) {
    //     super(__getWsdlLocation(), CGWEBSERVICE_QNAME, features);
    // }

    public CGWebService(URL wsdlLocation) {
        super(wsdlLocation, CGWEBSERVICE_QNAME);
    }

    //  public CGWebService(URL wsdlLocation, WebServiceFeature... features) {
    //      super(wsdlLocation, CGWEBSERVICE_QNAME, features);
    //  }

    public CGWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    // public CGWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    //     super(wsdlLocation, serviceName, features);
    // }

    /**
     * @return returns CGWebServiceInterface
     */
    @WebEndpoint(name = "CGWebServiceInterfacePort")
    public CGWebServiceInterface getCGWebServiceInterfacePort() {
        return super.getPort(new QName("urn:lk.dialog.cg.ws", "CGWebServiceInterfacePort"), CGWebServiceInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CGWebServiceInterface
     */
    @WebEndpoint(name = "CGWebServiceInterfacePort")
    public CGWebServiceInterface getCGWebServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:lk.dialog.cg.ws", "CGWebServiceInterfacePort"), CGWebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CGWEBSERVICE_EXCEPTION != null) {
            throw CGWEBSERVICE_EXCEPTION;
        }
        return CGWEBSERVICE_WSDL_LOCATION;
    }

}
